import asyncio
from typing import List, Dict, Any
from pydantic import BaseModel, Field

from google.antigravity import Agent, LocalAgentConfig

# Importing module-specific schemas
from agents.code_reviewer.schema import CodeReviewReport
from agents.ml_guardian.schema import MLOpsReport
from agents.iso_compliance.schema import ISOComplianceReport

# Importing tools
from agents.code_reviewer.tools import run_linter, get_git_diff
from agents.ml_guardian.tools import check_mlflow_metrics, validate_snowflake_schema
from agents.iso_compliance.tools import check_env_security_compliance

class FinalExecutiveReport(BaseModel):
    status: str = Field(description="Final deployment decision verdict: 'APPROVED', 'APPROVED_WITH_WARNINGS', or 'REJECTED'.")
    summary: str = Field(description="High-level executive summary consolidating findings from Engineering, MLOps, and ISO Compliance.")
    blocking_issues: List[str] = Field(default=[], description="Compiled list of critical blockers halting production deployment.")
    innovation_backlog: List[Dict[str, Any]] = Field(default=[], description="Aggregated innovation ideas generated by the council.")

async def run_specialized_agent(skill_path: str, response_schema: Any, tools: List[Any], context_data: str) -> str:
    config = LocalAgentConfig()
    with open(skill_path, "r", encoding="utf-8") as f:
        system_instruction = f.read()

    async with Agent(config, tools=tools) as agent:
        prompt = f"Perform a comprehensive evaluation on the following software snapshot:\n\n{context_data}"
        response = await agent.chat(
            prompt,
            system_instruction=system_instruction,
            response_schema=response_schema
        )
        return await response.text()

async def main():
    application_snapshot = """
    [CODE ARTIFACT - main.py]
    def predict_anomaly(sensor_payload):
        if sensor_payload['value'] > 80:
            if sensor_payload['type'] == 'vibration':
                return True
        return False
        
    [MLOPS METADATA]
    Model Architecture: TemporalConvolutionalAutoencoder
    Target Feature Store: SNOWFLAKE_PROD.MAINTENANCE.SENSOR_FEATURES
    MLflow Run ID: run_abc_12345
    """

    print("🚀 Dispatched 3 parallel evaluation agents via Antigravity 2.0 Engine...")

    # Concurrent Execution via Fan-Out Pattern (Now with 3 Agents!)
    code_task = run_specialized_agent(
        "agents/code_reviewer/prompt.md", 
        CodeReviewReport, 
        [run_linter, get_git_diff], 
        application_snapshot
    )
    ml_task = run_specialized_agent(
        "agents/ml_guardian/prompt.md", 
        MLOpsReport, 
        [check_mlflow_metrics, validate_snowflake_schema], 
        application_snapshot
    )
    iso_task = run_specialized_agent(
        "agents/iso_compliance/prompt.md", 
        ISOComplianceReport, 
        [check_env_security_compliance], 
        application_snapshot
    )

    # Await all 3 concurrent execution tasks smoothly
    report_code, report_ml, report_iso = await asyncio.gather(code_task, ml_task, iso_task)

    print("\n🧠 Consolidating subagent intelligence inside Central Orchestrator...")
    
    orchestrator_input = f"""
    Code Reviewer Subagent Report:
    {report_code}
    
    ML Guardian Subagent Report:
    {report_ml}
    
    ISO Compliance Subagent Report:
    {report_iso}
    """

    async with Agent(LocalAgentConfig()) as orchestrator:
        final_verdict = await orchestrator.chat(
            f"Consolidate the provided subagent analyses. Resolve data conflicts and populate the schema:\n\n{orchestrator_input}",
            system_instruction="You are the Principal Systems Architect. Evaluate inputs from specialized subagents (Engineering, MLOps, Regulations), decide if production deployment is blocked, and compile all forward-looking innovation backlog ideas.",
            response_schema=FinalExecutiveReport
        )
        
        print("\n📋 ============ FINAL EXECUTIVE DEPLOYMENT REPORT ============")
        print(await final_verdict.text())

if __name__ == "__main__":
    asyncio.run(main())